version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web/uploads:/var/www/html/uploads
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: finalexam
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
